name: cdgi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.2
  geolocator: ^10.1.0
  speech_to_text: ^7.0.0
  flutter_tts: ^3.8.5
  image_picker: ^1.0.4
  image: ^4.1.3
  http: ^1.1.0
  fpdart: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
